defaults:
  - _self_
  - schedulers:
      - RR
      - SJF
      - SP
      - MFQ
      - SPMFQ
      - MPMFQ

exp:
  n_repeats: 50
  uuid: ${now:%m%d_%H%M%S}
  save_dir: ${hydra:runtime.cwd}/logs/
  skip_single_var: true  # skip plot those vars with only one value. only plot var with provided range.


virtual_env:
  n_threads: 2


test_groups:
  _target_: scripts.evaluate.generate_test_groups
  n_processes_group:
    _target_: scripts.evaluate.get_params_group
    val_range: [10, 1000]
    n_groups: 5
    is_geometric: true

  lens_mean_normal_group:
    _target_: scripts.evaluate.get_params_group
    val_range: [40, 50]
    n_groups: 1

  lens_std_normal_group:
    _target_: scripts.evaluate.get_params_group
    val_range: [20]
    n_groups: 1

  density_group:
    _target_: scripts.evaluate.get_params_group
    val_range: [2]
    n_groups: 1
    is_integer: false

